### ISSUE TITLE
KeyError: 'user.view'

### ISSUE THREAD

**Issue by saifkazi** [Kalenis/kalenislims#22]
i was able to sucessfully setup the kalenislims but when i logged in i am getting the following error 

```
Traceback (most recent call last):
  File "/trytond-5.6.15-py3.8.egg/trytond/wsgi.py", line 115, in dispatch_request
    return endpoint(request, **request.view_args)
  File "/trytond-5.6.15-py3.8.egg/trytond/protocols/dispatcher.py", line 47, in rpc
    return methods.get(request.rpc_method, _dispatch)(
  File "/trytond-5.6.15-py3.8.egg/trytond/wsgi.py", line 82, in auth_required
    return wrapped(*args, **kwargs)
  File "/trytond-5.6.15-py3.8.egg/trytond/protocols/wrappers.py", line 131, in wrapper
    return func(request, pool, *args, **kwargs)
  File "/trytond-5.6.15-py3.8.egg/trytond/protocols/dispatcher.py", line 143, in _dispatch
    obj, method = get_object_method(request, pool)
  File "/trytond-5.6.15-py3.8.egg/trytond/protocols/dispatcher.py", line 130, in get_object_method
    return pool.get(name, type=type), method
  File "/trytond-5.6.15-py3.8.egg/trytond/pool.py", line 179, in get
    return self._pool[self.database_name][type][name]
KeyError: 'user.view'
```

any idea what i am doing wrong?

**Comment by ieparszyk** [comment]
Hi @saifkazi. You need to install the  [user_view module](https://github.com/Kalenis/kalenis_user_view). 
If you use pip,  `pip install kalenis-user-view`

Best

**Comment by saifkazi** [comment]
@ieparszyk  its tried installing it seems like it is already there

**Comment by ieparszyk** [comment]
@saifkazi great. Then you need to activate the module: `trytond-admin -c path_to_your_config -d your_db_name -u user_view`.

**Comment by saifkazi** [comment]
> 
> 
> @saifkazi great. Then you need to activate the module: `trytond-admin -c path_to_your_config -d your_db_name -u user_view`.

Thanks a lot this solves my issue
